[2022-01-19 20:01:32,834] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.update_processed_files_media_prepare manual__2022-01-19T20:01:15.496142+00:00 [queued]>
[2022-01-19 20:01:32,848] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.update_processed_files_media_prepare manual__2022-01-19T20:01:15.496142+00:00 [queued]>
[2022-01-19 20:01:32,848] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 20:01:32,849] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-19 20:01:32,849] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 20:01:32,862] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): update_processed_files_media_prepare> on 2022-01-19 20:01:15.496142+00:00
[2022-01-19 20:01:32,867] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2022-01-19 20:01:32,870] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'update_processed_files_media_prepare', 'manual__2022-01-19T20:01:15.496142+00:00', '--job-id', '2811', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpoc300vaw', '--error-file', '/tmp/tmpx2gq75gi']
[2022-01-19 20:01:32,871] {standard_task_runner.py:77} INFO - Job 2811: Subtask update_processed_files_media_prepare
[2022-01-19 20:01:32,925] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.update_processed_files_media_prepare manual__2022-01-19T20:01:15.496142+00:00 [running]> on host 218df5ddc363
[2022-01-19 20:01:33,003] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=update_processed_files_media_prepare
AIRFLOW_CTX_EXECUTION_DATE=2022-01-19T20:01:15.496142+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-19T20:01:15.496142+00:00
[2022-01-19 20:01:33,021] {python.py:152} INFO - Done. Returned value was: None
[2022-01-19 20:01:33,039] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=update_processed_files_media_prepare, execution_date=20220119T200115, start_date=20220119T200132, end_date=20220119T200133
[2022-01-19 20:01:33,083] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-19 20:01:33,186] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
