[2021-12-27 12:19:18,372] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.refactor_process manual__2021-12-27T12:19:08.248096+00:00 [queued]>
[2021-12-27 12:19:18,382] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.refactor_process manual__2021-12-27T12:19:08.248096+00:00 [queued]>
[2021-12-27 12:19:18,382] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-27 12:19:18,383] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-27 12:19:18,383] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-27 12:19:18,396] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): refactor_process> on 2021-12-27 12:19:08.248096+00:00
[2021-12-27 12:19:18,401] {standard_task_runner.py:52} INFO - Started process 3711 to run task
[2021-12-27 12:19:18,404] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'refactor_process', 'manual__2021-12-27T12:19:08.248096+00:00', '--job-id', '1607', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmprqdlpbf2', '--error-file', '/tmp/tmppms5zbxu']
[2021-12-27 12:19:18,406] {standard_task_runner.py:77} INFO - Job 1607: Subtask refactor_process
[2021-12-27 12:19:18,448] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.refactor_process manual__2021-12-27T12:19:08.248096+00:00 [running]> on host 218df5ddc363
[2021-12-27 12:19:18,498] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=refactor_process
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T12:19:08.248096+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-27T12:19:08.248096+00:00
[2021-12-27 12:19:18,552] {python.py:152} INFO - Done. Returned value was: None
[2021-12-27 12:19:18,563] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=refactor_process, execution_date=20211227T121908, start_date=20211227T121918, end_date=20211227T121918
[2021-12-27 12:19:18,617] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-27 12:19:18,667] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
