[2022-01-03 01:46:28,426] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.delete_working_files manual__2022-01-03T01:44:51.345463+00:00 [queued]>
[2022-01-03 01:46:28,440] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.delete_working_files manual__2022-01-03T01:44:51.345463+00:00 [queued]>
[2022-01-03 01:46:28,440] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 01:46:28,441] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-03 01:46:28,441] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 01:46:28,454] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): delete_working_files> on 2022-01-03 01:44:51.345463+00:00
[2022-01-03 01:46:28,460] {standard_task_runner.py:52} INFO - Started process 6865 to run task
[2022-01-03 01:46:28,464] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'delete_working_files', 'manual__2022-01-03T01:44:51.345463+00:00', '--job-id', '2260', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpitzspu7i', '--error-file', '/tmp/tmpb2tuvbbc']
[2022-01-03 01:46:28,465] {standard_task_runner.py:77} INFO - Job 2260: Subtask delete_working_files
[2022-01-03 01:46:28,514] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.delete_working_files manual__2022-01-03T01:44:51.345463+00:00 [running]> on host 218df5ddc363
[2022-01-03 01:46:28,593] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=delete_working_files
AIRFLOW_CTX_EXECUTION_DATE=2022-01-03T01:44:51.345463+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-03T01:44:51.345463+00:00
[2022-01-03 01:46:28,627] {python.py:152} INFO - Done. Returned value was: None
[2022-01-03 01:46:28,650] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=delete_working_files, execution_date=20220103T014451, start_date=20220103T014628, end_date=20220103T014628
[2022-01-03 01:46:28,716] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-03 01:46:28,757] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
