[2021-12-08 23:39:58,867] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_imageFile manual__2021-12-08T23:39:55.760948+00:00 [queued]>
[2021-12-08 23:39:58,905] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_imageFile manual__2021-12-08T23:39:55.760948+00:00 [queued]>
[2021-12-08 23:39:58,919] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 23:39:58,925] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-08 23:39:58,926] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 23:39:58,988] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): check_imageFile> on 2021-12-08 23:39:55.760948+00:00
[2021-12-08 23:39:59,006] {standard_task_runner.py:52} INFO - Started process 7243 to run task
[2021-12-08 23:39:59,023] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'check_imageFile', 'manual__2021-12-08T23:39:55.760948+00:00', '--job-id', '647', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmn63so2e', '--error-file', '/tmp/tmpv_470a0y']
[2021-12-08 23:39:59,027] {standard_task_runner.py:77} INFO - Job 647: Subtask check_imageFile
[2021-12-08 23:39:59,195] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.check_imageFile manual__2021-12-08T23:39:55.760948+00:00 [running]> on host b5fd0372bf6e
[2021-12-08 23:39:59,356] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=check_imageFile
AIRFLOW_CTX_EXECUTION_DATE=2021-12-08T23:39:55.760948+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-08T23:39:55.760948+00:00
[2021-12-08 23:39:59,358] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-08 23:39:59,361] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sha256sum /opt/***/official_data/Image.csv']
[2021-12-08 23:39:59,401] {subprocess.py:85} INFO - Output:
[2021-12-08 23:39:59,427] {subprocess.py:89} INFO - e891870a24e5a22c9520c5d417af923366083a3617288cafa3cc18e3fed77b11  /opt/***/official_data/Image.csv
[2021-12-08 23:39:59,429] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-08 23:39:59,498] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=check_imageFile, execution_date=20211208T233955, start_date=20211208T233958, end_date=20211208T233959
[2021-12-08 23:39:59,554] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 23:39:59,675] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
