[2022-01-02 18:38:13,216] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.delete_working_files manual__2022-01-02T18:37:22.208141+00:00 [queued]>
[2022-01-02 18:38:13,231] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.delete_working_files manual__2022-01-02T18:37:22.208141+00:00 [queued]>
[2022-01-02 18:38:13,231] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-02 18:38:13,232] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-02 18:38:13,232] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-02 18:38:13,249] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): delete_working_files> on 2022-01-02 18:37:22.208141+00:00
[2022-01-02 18:38:13,254] {standard_task_runner.py:52} INFO - Started process 11284 to run task
[2022-01-02 18:38:13,259] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'delete_working_files', 'manual__2022-01-02T18:37:22.208141+00:00', '--job-id', '1843', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmprtywg4u8', '--error-file', '/tmp/tmpzlhd6j89']
[2022-01-02 18:38:13,261] {standard_task_runner.py:77} INFO - Job 1843: Subtask delete_working_files
[2022-01-02 18:38:13,318] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.delete_working_files manual__2022-01-02T18:37:22.208141+00:00 [running]> on host 218df5ddc363
[2022-01-02 18:38:13,386] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=delete_working_files
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T18:37:22.208141+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-02T18:37:22.208141+00:00
[2022-01-02 18:38:13,453] {python.py:152} INFO - Done. Returned value was: None
[2022-01-02 18:38:13,492] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=delete_working_files, execution_date=20220102T183722, start_date=20220102T183813, end_date=20220102T183813
[2022-01-02 18:38:13,552] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-02 18:38:13,623] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
