[2021-12-08 14:42:15,922] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-06-30T00:00:00+00:00 [queued]>
[2021-12-08 14:42:16,153] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-06-30T00:00:00+00:00 [queued]>
[2021-12-08 14:42:16,155] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:42:16,164] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-08 14:42:16,171] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:42:16,453] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): check_file> on 2021-06-30 00:00:00+00:00
[2021-12-08 14:42:16,473] {standard_task_runner.py:52} INFO - Started process 114 to run task
[2021-12-08 14:42:16,527] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'check_file', 'scheduled__2021-06-30T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp7rh_7r80', '--error-file', '/tmp/tmp39hk2m4n']
[2021-12-08 14:42:16,529] {standard_task_runner.py:77} INFO - Job 90: Subtask check_file
[2021-12-08 14:42:17,102] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.check_file scheduled__2021-06-30T00:00:00+00:00 [running]> on host 6ff10d26dc07
[2021-12-08 14:42:17,995] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=check_file
AIRFLOW_CTX_EXECUTION_DATE=2021-06-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-30T00:00:00+00:00
[2021-12-08 14:42:18,035] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-08 14:42:18,048] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sha256sum /opt/***/official_data/test.csv']
[2021-12-08 14:42:18,148] {subprocess.py:85} INFO - Output:
[2021-12-08 14:42:32,290] {subprocess.py:89} INFO - 6658e41458ff02775f57e8d8f407a0e62966d5cf65680690cb8da28db866e38c  /opt/***/official_data/test.csv
[2021-12-08 14:42:32,301] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-08 14:42:32,570] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=check_file, execution_date=20210630T000000, start_date=20211208T144215, end_date=20211208T144232
[2021-12-08 14:42:32,844] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 14:42:37,674] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
