[2022-01-20 12:04:16,929] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.col_process_image manual__2022-01-20T12:04:08.140839+00:00 [queued]>
[2022-01-20 12:04:16,947] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.col_process_image manual__2022-01-20T12:04:08.140839+00:00 [queued]>
[2022-01-20 12:04:16,948] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-20 12:04:16,948] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-20 12:04:16,948] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-20 12:04:16,965] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): col_process_image> on 2022-01-20 12:04:08.140839+00:00
[2022-01-20 12:04:16,971] {standard_task_runner.py:52} INFO - Started process 685 to run task
[2022-01-20 12:04:16,975] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'col_process_image', 'manual__2022-01-20T12:04:08.140839+00:00', '--job-id', '2856', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpnm4cetdo', '--error-file', '/tmp/tmp6f4qe53s']
[2022-01-20 12:04:16,976] {standard_task_runner.py:77} INFO - Job 2856: Subtask col_process_image
[2022-01-20 12:04:17,027] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.col_process_image manual__2022-01-20T12:04:08.140839+00:00 [running]> on host 218df5ddc363
[2022-01-20 12:04:17,091] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=col_process_image
AIRFLOW_CTX_EXECUTION_DATE=2022-01-20T12:04:08.140839+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-20T12:04:08.140839+00:00
[2022-01-20 12:04:17,123] {python.py:152} INFO - Done. Returned value was: None
[2022-01-20 12:04:17,141] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=col_process_image, execution_date=20220120T120408, start_date=20220120T120416, end_date=20220120T120417
[2022-01-20 12:04:17,187] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-20 12:04:17,262] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
