[2021-12-29 23:24:14,250] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.delete_working_files manual__2021-12-29T23:23:20.174381+00:00 [queued]>
[2021-12-29 23:24:14,279] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.delete_working_files manual__2021-12-29T23:23:20.174381+00:00 [queued]>
[2021-12-29 23:24:14,281] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 23:24:14,283] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-29 23:24:14,284] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 23:24:14,316] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): delete_working_files> on 2021-12-29 23:23:20.174381+00:00
[2021-12-29 23:24:14,334] {standard_task_runner.py:52} INFO - Started process 14194 to run task
[2021-12-29 23:24:14,350] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'delete_working_files', 'manual__2021-12-29T23:23:20.174381+00:00', '--job-id', '1665', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpu3kca2bv', '--error-file', '/tmp/tmp9wxpsj28']
[2021-12-29 23:24:14,355] {standard_task_runner.py:77} INFO - Job 1665: Subtask delete_working_files
[2021-12-29 23:24:14,555] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.delete_working_files manual__2021-12-29T23:23:20.174381+00:00 [running]> on host 218df5ddc363
[2021-12-29 23:24:14,670] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=delete_working_files
AIRFLOW_CTX_EXECUTION_DATE=2021-12-29T23:23:20.174381+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-29T23:23:20.174381+00:00
[2021-12-29 23:24:14,680] {python.py:152} INFO - Done. Returned value was: None
[2021-12-29 23:24:14,706] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=delete_working_files, execution_date=20211229T232320, start_date=20211229T232414, end_date=20211229T232414
[2021-12-29 23:24:14,778] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-29 23:24:14,850] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
