[2021-12-08 14:45:46,013] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-07-25T00:00:00+00:00 [queued]>
[2021-12-08 14:45:46,098] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-07-25T00:00:00+00:00 [queued]>
[2021-12-08 14:45:46,099] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:45:46,100] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-08 14:45:46,112] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:45:46,252] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): check_file> on 2021-07-25 00:00:00+00:00
[2021-12-08 14:45:46,262] {standard_task_runner.py:52} INFO - Started process 243 to run task
[2021-12-08 14:45:46,268] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'check_file', 'scheduled__2021-07-25T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmplziv04o5', '--error-file', '/tmp/tmp3ex7nwv7']
[2021-12-08 14:45:46,271] {standard_task_runner.py:77} INFO - Job 145: Subtask check_file
[2021-12-08 14:45:46,491] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.check_file scheduled__2021-07-25T00:00:00+00:00 [running]> on host 6ff10d26dc07
[2021-12-08 14:45:46,939] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=check_file
AIRFLOW_CTX_EXECUTION_DATE=2021-07-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-25T00:00:00+00:00
[2021-12-08 14:45:46,942] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-08 14:45:46,949] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sha256sum /opt/***/official_data/test.csv']
[2021-12-08 14:45:47,097] {subprocess.py:85} INFO - Output:
[2021-12-08 14:45:58,090] {subprocess.py:89} INFO - 6658e41458ff02775f57e8d8f407a0e62966d5cf65680690cb8da28db866e38c  /opt/***/official_data/test.csv
[2021-12-08 14:45:58,134] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-08 14:45:59,166] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=check_file, execution_date=20210725T000000, start_date=20211208T144546, end_date=20211208T144559
[2021-12-08 14:45:59,251] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 14:45:59,514] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
