[2021-12-08 14:57:31,258] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-10-03T00:00:00+00:00 [queued]>
[2021-12-08 14:57:31,295] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-10-03T00:00:00+00:00 [queued]>
[2021-12-08 14:57:31,295] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:57:31,297] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-08 14:57:31,302] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:57:31,358] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): check_file> on 2021-10-03 00:00:00+00:00
[2021-12-08 14:57:31,376] {standard_task_runner.py:52} INFO - Started process 695 to run task
[2021-12-08 14:57:31,387] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'check_file', 'scheduled__2021-10-03T00:00:00+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmy3bdny8', '--error-file', '/tmp/tmp9790x1cy']
[2021-12-08 14:57:31,390] {standard_task_runner.py:77} INFO - Job 303: Subtask check_file
[2021-12-08 14:57:31,507] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.check_file scheduled__2021-10-03T00:00:00+00:00 [running]> on host 8edf9af2b560
[2021-12-08 14:57:31,703] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=check_file
AIRFLOW_CTX_EXECUTION_DATE=2021-10-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-03T00:00:00+00:00
[2021-12-08 14:57:31,709] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-08 14:57:31,712] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sha256sum /opt/***/official_data/test.csv']
[2021-12-08 14:57:31,748] {subprocess.py:85} INFO - Output:
[2021-12-08 14:57:35,475] {subprocess.py:89} INFO - 6658e41458ff02775f57e8d8f407a0e62966d5cf65680690cb8da28db866e38c  /opt/***/official_data/test.csv
[2021-12-08 14:57:35,476] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-08 14:57:35,539] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=check_file, execution_date=20211003T000000, start_date=20211208T145731, end_date=20211208T145735
[2021-12-08 14:57:35,607] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 14:57:35,679] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
