[2022-01-03 01:06:17,595] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.database_processing_media_prepare manual__2022-01-03T01:05:43.261682+00:00 [queued]>
[2022-01-03 01:06:17,610] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.database_processing_media_prepare manual__2022-01-03T01:05:43.261682+00:00 [queued]>
[2022-01-03 01:06:17,611] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 01:06:17,611] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-03 01:06:17,611] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 01:06:17,627] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): database_processing_media_prepare> on 2022-01-03 01:05:43.261682+00:00
[2022-01-03 01:06:17,633] {standard_task_runner.py:52} INFO - Started process 4856 to run task
[2022-01-03 01:06:17,637] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'database_processing_media_prepare', 'manual__2022-01-03T01:05:43.261682+00:00', '--job-id', '2170', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpwoh6gxpr', '--error-file', '/tmp/tmpfvk1_la2']
[2022-01-03 01:06:17,639] {standard_task_runner.py:77} INFO - Job 2170: Subtask database_processing_media_prepare
[2022-01-03 01:06:17,695] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.database_processing_media_prepare manual__2022-01-03T01:05:43.261682+00:00 [running]> on host 218df5ddc363
[2022-01-03 01:06:17,763] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=database_processing_media_prepare
AIRFLOW_CTX_EXECUTION_DATE=2022-01-03T01:05:43.261682+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-03T01:05:43.261682+00:00
[2022-01-03 01:06:18,332] {logging_mixin.py:109} INFO - You're connected to database
[2022-01-03 01:06:19,096] {python.py:152} INFO - Done. Returned value was: None
[2022-01-03 01:06:19,113] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=database_processing_media_prepare, execution_date=20220103T010543, start_date=20220103T010617, end_date=20220103T010619
[2022-01-03 01:06:19,142] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-03 01:06:19,200] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
