[2021-12-08 14:53:09,950] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process scheduled__2021-08-27T00:00:00+00:00 [queued]>
[2021-12-08 14:53:10,127] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process scheduled__2021-08-27T00:00:00+00:00 [queued]>
[2021-12-08 14:53:10,133] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:53:10,168] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-08 14:53:10,214] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:53:10,310] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): pre_process> on 2021-08-27 00:00:00+00:00
[2021-12-08 14:53:10,350] {standard_task_runner.py:52} INFO - Started process 311 to run task
[2021-12-08 14:53:10,367] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'pre_process', 'scheduled__2021-08-27T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp9vo0dv0m', '--error-file', '/tmp/tmp7_pi9l8e']
[2021-12-08 14:53:10,373] {standard_task_runner.py:77} INFO - Job 231: Subtask pre_process
[2021-12-08 14:53:10,792] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.pre_process scheduled__2021-08-27T00:00:00+00:00 [running]> on host 8edf9af2b560
[2021-12-08 14:53:11,071] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=pre_process
AIRFLOW_CTX_EXECUTION_DATE=2021-08-27T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-27T00:00:00+00:00
[2021-12-08 14:53:33,048] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:162: DtypeWarning: Columns (0,1,2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2021-12-08 14:53:36,858] {python.py:152} INFO - Done. Returned value was: None
[2021-12-08 14:53:37,002] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=pre_process, execution_date=20210827T000000, start_date=20211208T145309, end_date=20211208T145337
[2021-12-08 14:53:37,239] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 14:53:37,516] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
