[2022-02-07 11:59:27,987] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.database_processing_image scheduled__2022-02-06T00:00:00+00:00 [queued]>
[2022-02-07 11:59:28,014] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.database_processing_image scheduled__2022-02-06T00:00:00+00:00 [queued]>
[2022-02-07 11:59:28,014] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 11:59:28,015] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-02-07 11:59:28,015] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 11:59:28,043] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): database_processing_image> on 2022-02-06 00:00:00+00:00
[2022-02-07 11:59:28,051] {standard_task_runner.py:52} INFO - Started process 126 to run task
[2022-02-07 11:59:28,058] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'database_processing_image', 'scheduled__2022-02-06T00:00:00+00:00', '--job-id', '3292', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmvvjz8qh', '--error-file', '/tmp/tmpu966nw7x']
[2022-02-07 11:59:28,061] {standard_task_runner.py:77} INFO - Job 3292: Subtask database_processing_image
[2022-02-07 11:59:28,155] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.database_processing_image scheduled__2022-02-06T00:00:00+00:00 [running]> on host 218df5ddc363
[2022-02-07 11:59:28,275] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=database_processing_image
AIRFLOW_CTX_EXECUTION_DATE=2022-02-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-06T00:00:00+00:00
[2022-02-07 11:59:28,278] {python.py:152} INFO - Done. Returned value was: None
[2022-02-07 11:59:28,332] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=database_processing_image, execution_date=20220206T000000, start_date=20220207T115927, end_date=20220207T115928
[2022-02-07 11:59:28,385] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-07 11:59:28,585] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
