[2021-12-13 11:39:46,629] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.refactor_process manual__2021-12-13T11:39:35.475230+00:00 [queued]>
[2021-12-13 11:39:46,639] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.refactor_process manual__2021-12-13T11:39:35.475230+00:00 [queued]>
[2021-12-13 11:39:46,640] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 11:39:46,640] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-13 11:39:46,640] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 11:39:46,654] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): refactor_process> on 2021-12-13 11:39:35.475230+00:00
[2021-12-13 11:39:46,659] {standard_task_runner.py:52} INFO - Started process 871 to run task
[2021-12-13 11:39:46,662] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'refactor_process', 'manual__2021-12-13T11:39:35.475230+00:00', '--job-id', '882', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpo7el81z7', '--error-file', '/tmp/tmpwf2bnhb8']
[2021-12-13 11:39:46,663] {standard_task_runner.py:77} INFO - Job 882: Subtask refactor_process
[2021-12-13 11:39:46,708] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.refactor_process manual__2021-12-13T11:39:35.475230+00:00 [running]> on host 218df5ddc363
[2021-12-13 11:39:46,759] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=refactor_process
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T11:39:35.475230+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-13T11:39:35.475230+00:00
[2021-12-13 11:39:46,817] {python.py:152} INFO - Done. Returned value was: None
[2021-12-13 11:39:46,830] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=refactor_process, execution_date=20211213T113935, start_date=20211213T113946, end_date=20211213T113946
[2021-12-13 11:39:46,875] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-13 11:39:46,930] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
